Repository rollerworks/PasswordStrengthValidator, pull requests merged in 2021-06, with the labels that each got.

#46 Fix brazilian portuguese translations
  src/Resources/translations/validators.pt_BR.xlf
Labels: Translation

#48 Remove support for PHP 7.1 and fix deprecations
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yaml
  Makefile
  composer.json
  phpunit.xml.dist
  src/Validator/Constraints/PasswordStrengthValidator.php
  tests/BlackListMockProviderTrait.php
  tests/Blacklist/SqliteProviderTest.php
  tests/Command/BlacklistCommandTest.php
  tests/Command/BlacklistCommandTestCase.php
  tests/Command/BlacklistDeleteCommandTest.php
  tests/Command/BlacklistListCommandTest.php
  tests/Command/BlacklistPurgeCommandTest.php
  tests/Command/BlacklistUpdateCommandTest.php
  tests/P0wnedPassword/Request/ClientTest.php
  tests/Validator/BlacklistValidationTest.php
  tests/Validator/P0wnedPasswordValidatorTest.php
Labels: BC Break, Enhancement

#47 Add PHP 8 attributes
  src/Validator/Constraints/Blacklist.php
  src/Validator/Constraints/PasswordRequirements.php
  src/Validator/Constraints/PasswordStrength.php
Labels: Feature
